require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LogFilesController do

  # This should return the minimal set of attributes required to create a valid
  # LogFile. As you add validations to LogFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "file_name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LogFilesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all log_files as @log_files" do
      log_file = LogFile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:log_files).should eq([log_file])
    end
  end

  describe "GET show" do
    it "assigns the requested log_file as @log_file" do
      log_file = LogFile.create! valid_attributes
      get :show, {:id => log_file.to_param}, valid_session
      assigns(:log_file).should eq(log_file)
    end
  end

  describe "GET new" do
    it "assigns a new log_file as @log_file" do
      get :new, {}, valid_session
      assigns(:log_file).should be_a_new(LogFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested log_file as @log_file" do
      log_file = LogFile.create! valid_attributes
      get :edit, {:id => log_file.to_param}, valid_session
      assigns(:log_file).should eq(log_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LogFile" do
        expect {
          post :create, {:log_file => valid_attributes}, valid_session
        }.to change(LogFile, :count).by(1)
      end

      it "assigns a newly created log_file as @log_file" do
        post :create, {:log_file => valid_attributes}, valid_session
        assigns(:log_file).should be_a(LogFile)
        assigns(:log_file).should be_persisted
      end

      it "redirects to the created log_file" do
        post :create, {:log_file => valid_attributes}, valid_session
        response.should redirect_to(LogFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved log_file as @log_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        LogFile.any_instance.stub(:save).and_return(false)
        post :create, {:log_file => { "file_name" => "invalid value" }}, valid_session
        assigns(:log_file).should be_a_new(LogFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LogFile.any_instance.stub(:save).and_return(false)
        post :create, {:log_file => { "file_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested log_file" do
        log_file = LogFile.create! valid_attributes
        # Assuming there are no other log_files in the database, this
        # specifies that the LogFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LogFile.any_instance.should_receive(:update_attributes).with({ "file_name" => "MyString" })
        put :update, {:id => log_file.to_param, :log_file => { "file_name" => "MyString" }}, valid_session
      end

      it "assigns the requested log_file as @log_file" do
        log_file = LogFile.create! valid_attributes
        put :update, {:id => log_file.to_param, :log_file => valid_attributes}, valid_session
        assigns(:log_file).should eq(log_file)
      end

      it "redirects to the log_file" do
        log_file = LogFile.create! valid_attributes
        put :update, {:id => log_file.to_param, :log_file => valid_attributes}, valid_session
        response.should redirect_to(log_file)
      end
    end

    describe "with invalid params" do
      it "assigns the log_file as @log_file" do
        log_file = LogFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LogFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => log_file.to_param, :log_file => { "file_name" => "invalid value" }}, valid_session
        assigns(:log_file).should eq(log_file)
      end

      it "re-renders the 'edit' template" do
        log_file = LogFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LogFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => log_file.to_param, :log_file => { "file_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested log_file" do
      log_file = LogFile.create! valid_attributes
      expect {
        delete :destroy, {:id => log_file.to_param}, valid_session
      }.to change(LogFile, :count).by(-1)
    end

    it "redirects to the log_files list" do
      log_file = LogFile.create! valid_attributes
      delete :destroy, {:id => log_file.to_param}, valid_session
      response.should redirect_to(log_files_url)
    end
  end

end
